name = "drive"
type = "webpack"
workers_dev = true
account_id = "5c6f621c614f92723ecf0c80662d9886"
zone_id = "6c416fe2b6a99cdca4a5ebdc64114eb3"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "55b0fc4e288a465fb225421f2af5d445", id = "09b0cf433f394b309d35d1ff3bd0bf39" }
]

[env.staging]
name = "drive-staging"
