name = "drive"
type = "webpack"
workers_dev = true
account_id = "5c6f621c614f92723ecf0c80662d9886"
zone_id = "6c416fe2b6a99cdca4a5ebdc64114eb3"
kv_namespaces = [
    { binding = "BUCKET", id = "8602a8d135fe49e4807e2c66e8d39f9b" }
]

[env.staging]
name = "drive-staging"
